---
- name: add flathub remote (user)
  become_user: "{{ user.name }}"
  community.general.flatpak_remote:
    name: flathub
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    state: present
    method: user

- name: Install flatpak packages (user)
  become_user: "{{ user.name }}"
  when: homedir.flatpaks is defined and homedir.flatpaks is iterable and homedir.flatpaks|length > 0
  community.general.flatpak:
    name: "{{ homedir.flatpaks }}"
    state: present
    method: user
