---
- name: install grub packages
  tags: '@00-core/bootloader'
  community.general.pacman:
    name: [grub, efibootmgr]
    state: present

- name: install grub on the boot storage device
  tags: '@00-core/bootloader'
  ansible.builtin.command: grub-install --target=i386-pc --recheck {{ boot.storage_device }}

- name: install the grub efi application
  tags: '@00-core/bootloader'
  ansible.builtin.command: grub-install --target=x86_64-efi --efi-directory /boot --removable

- name: generate the grub config
  tags: '@00-core/bootloader'
  ansible.builtin.command: grub-mkconfig -o /boot/grub/grub.cfg
