---
- name: create mkinitcpio config
  ansible.builtin.copy:
    content: "HOOKS=({{ kernel.hooks }})"
    dest: /etc/mkinitcpio.conf
    force: true

- name: run mkinitcpio
  ansible.builtin.command: "mkinitcpio -p {{ kernel.name }}"

- name: configure kernel parameters at boot
  ansible.builtin.copy:
    src: sysctl.d/
    dest: /etc/sysctl.d
